repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: end-of-file-fixer
    - id: check-docstring-first
    - id: debug-statements
    - id: name-tests-test
    - id: requirements-txt-fixer
    - id: mixed-line-ending
    - id: detect-private-key
    - id: destroyed-symlinks
    - id: check-symlinks
    - id: check-shebang-scripts-are-executable
    - id: check-case-conflict
    - id: check-added-large-files
    - id: name-tests-test

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.5
  hooks:
    - id: forbid-binary
    - id: git-check
    - id: shellcheck
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.37.2
    hooks:
    - id: pyupgrade
      args: [--py36-plus]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.2
    hooks:
    - id: reorder-python-imports
      args: [--py3-plus]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
    - id: autopep8
repos:
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3.8
- repo: https://github.com/PyCQA/prospector
  rev: v1.8.4
  hooks:
      - id: prospector
        additional_dependencies:
          - "prospector[with_everything]"
          # the following are needed to run mypy successfully in the pre-commit virtualenv
          - types-setuptools
          - types-PyYAML
        args:
          - --summary-only
          - --with-tool=mypy
          - --with-tool=bandit
          - --zero-exit
